#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-vm-vnfm-migration.name" . }}-{{ template "eric-vm-vnfm-migration.privileged.cluster.role.name" . }}-psp-binding
  labels:
    app: {{ template "eric-vm-vnfm-migration.name" . }}
    chart: {{ template "eric-vm-vnfm-migration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- include "eric-vm-vnfm-migration.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-vm-vnfm-migration.helm-annotations" .| nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-vm-vnfm-migration.privileged.cluster.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-vm-vnfm-migration.name" . }}-sa