--*******************************************************************************
--* COPYRIGHT Ericsson 2022
--*
--* The copyright to the computer program(s) herein is the property of
--* Ericsson Inc. The programs may be used and/or copied only with written
--* permission from Ericsson Inc. or in accordance with the terms and
--* conditions stipulated in the agreement/contract under which the
--* program(s) have been supplied.
--*******************************************************************************
-- This sql script is common script and whenever there is new addition in schema append the content in this script.

-- Update this SQL file whenever their is change in wfsdb schema as after db restore,
-- the vnflcm db schema will override the vmvnfm db schema